# TODO: Structure
# 1. REMOVE SPURS FROM SKELETON
# 2. CREATE GRAPH
# 3. CONVERT PIXEL COORDINATES TO GEOFRAPHIC COORDINATES
    # (IT MUST ALSO BE THOUGHT ABOUT HOW THIS CAN WORK ON THINGS THAT ARENT RIVERS, BUT JUST A MASK)
# 4. LOWER THE RESULUTION OF THE GRAPH 
# 5. SAVE GRAPF